# Generated by Django 6.0.3 on 2026-03-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_positive', models.PositiveIntegerField(default=0, verbose_name='A+')),
                ('a_negative', models.PositiveIntegerField(default=0, verbose_name='A-')),
                ('b_positive', models.PositiveIntegerField(default=0, verbose_name='B+')),
                ('b_negative', models.PositiveIntegerField(default=0, verbose_name='B-')),
                ('o_positive', models.PositiveIntegerField(default=0, verbose_name='O+')),
                ('o_negative', models.PositiveIntegerField(default=0, verbose_name='O-')),
                ('ab_positive', models.PositiveIntegerField(default=0, verbose_name='AB+')),
                ('ab_negative', models.PositiveIntegerField(default=0, verbose_name='AB-')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blood Stock',
                'verbose_name_plural': 'Blood Stocks',
            },
        ),
        migrations.CreateModel(
            name='HospitalEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('technician', 'Lab Technician'), ('admin', 'Administrator'), ('blood_bank_officer', 'Blood Bank Officer')], max_length=30)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('contact_number', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('blood_bank_available', models.BooleanField(default=True)),
                ('has_24hr_service', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital Profile',
                'verbose_name_plural': 'Hospital Profiles',
            },
        ),
    ]
