# Generated by Django 6.0.3 on 2026-03-08 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=3)),
                ('rh_factor', models.CharField(choices=[('+', 'Positive (+)'), ('-', 'Negative (-)')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('any_disease', models.TextField(blank=True)),
                ('previous_injury', models.TextField(blank=True)),
                ('current_health_condition', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('last_blood_donation_date', models.DateField(blank=True, null=True)),
                ('last_donation_hospital', models.CharField(blank=True, max_length=200)),
                ('total_donations', models.PositiveIntegerField(default=0)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('cooldown', 'In Cooldown Period')], default='available', max_length=20)),
                ('willing_to_travel', models.BooleanField(default=True)),
                ('max_travel_distance', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donor Profile',
            },
        ),
        migrations.CreateModel(
            name='BloodDonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('hospital_name', models.CharField(max_length=200)),
                ('units_donated', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('verified_by_hospital', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood_requests.bloodrequest')),
            ],
            options={
                'ordering': ['-donation_date'],
            },
        ),
    ]
