# Generated by Django 6.0.3 on 2026-03-08 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='blood_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_responses', to='blood_requests.bloodrequest'),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='donorresponse',
            unique_together={('blood_request', 'donor')},
        ),
    ]
